#!/bin/bash
set -ex
out_conf=home

sleep 5

# [ ! "$HOST" = "svwork" ] && exit

# reach_gateway() {
#   ip neigh show dev wlan0 to $1 | grep REACHABLE &>/dev/null
# }
reach_gateway() {
  ip a | grep '178.55\|178.65\|178.97'
}

# see if at work
if ! reach_gateway 192.168.99.1
then
  out_conf=work
# elif
#   reach_gateway 192.168.178.1
# then
#   out_conf=home
fi

if [ "$out_conf" = "work" ]
then
  # Work
  # swaymsg output DP-1 resolution 1920x1080 position 1920 800
  swaymsg output DP-3 resolution 1920x1080 position 0 0
  swaymsg output eDP-1 resolution 1920x1080 position 1920 760
  # echo work > /tmp/sway_output_conf
else
  # Home
  swaymsg output DP-3 position 0 0 adaptive_sync on mode 3440x1440@99.943001Hz
  #swaymsg output DP-2 position 0 0 adaptive_sync on mode 2560x1080@99.943001Hz
  # output $fhd mode 1920x1080@74.924004Hz position 0 0
# output $fhd resolution 1920x1080 position 3440 261
  swaymsg output HDMI-A-1 mode 1920x1080@74.924004Hz position 3440 120
  swaymsg output eDP-1 resolution 1920x1080 position 3440 950
  #swaymsg output eDP-1 resolution 1920x1080 position 2560 900
  # echo home > /tmp/sway_output_conf
fi
