#!/bin/bash
set -ex
out_conf=home

sleep 2

# reach_gateway() {
#   ip neigh show dev wlan0 to $1 | grep REACHABLE &>/dev/null
# }
reach_gateway() {
	ip a | grep '192.168.99.'
}

if [ "$(cat /etc/hostname)" = "x2sixty" ]; then
	swaymsg output DP-1 mode 1920x1080@74.924Hz position 0 0
	swaymsg output eDP-1 resolution 1920x1080 position 0 0
fi

if [ "$(cat /etc/hostname)" = "hex" ]; then
	#AOC 3440x1440@99.982Hz
	swaymsg output DP-3 \
		mode 3440x1440@99.982Hz \
		adaptive_sync off \
		position 1920 0

	swaymsg output DP-1 \
		mode 3440x1440@99.982Hz \
		adaptive_sync off \
		position 1920 0
	#AOC 1080p@75.025Hz
	swaymsg output HDMI-A-1 \
		resolution 1920x1080@75.025Hz \
		adaptive_sync off \
		position 0 600
	#position 0 0
	#swaymsg create_output HEADLESS-1
	#swaymsg output HEADLESS-1 \
	#	mode 1920x1080@60Hz
	#sunshine_sway
fi
