bar:
  height: 26
  location: bottom
  background: 00000088

  center:
    - clock:
        content:
          - string: {text: , font: "monospace:style=solid:size=20"}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: "monospace:style=solid:size=20"}
          - string: {text: "{time}"}
