#!/bin/sh
pkill sxhkd ; pkill picom ; pkill dunst
sxhkd &
picom --experimental-backends &
dunst &
$HOME/.fehbg &
# bspc monitor DP-2 -d  
bspc monitor HDMI2  -d I   II  III IV V VI  
bspc monitor eDP1 -d VII IIX IX  X 
 

bspc config border_width               1
bspc config focused_border_color       "#889999"
bspc config window_gap                 10

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true

bspc config pointer_follows_monitor    true
bspc config pointer_follows_focus      false

bspc rule -a "chromium" desktop='^1'   focus=on
bspc rule -a "Code"     desktop='^2'
bspc rule -a "Slack"    desktop='^10'  focus=on

bspc rule -a firefox state=tiled
bspc rule -a Zathura state=tiled
#bspc rule -o -a stpopup state=floating rectangle=1918x380+0+$(expr 1078 - $(pgrep stpopup -f -c) \* 380)
bspc rule -a stpopup    state=floating rectangle=1918x380+0+698
bspc rule -a player     state=floating rectangle=500x380+1418+698
bspc rule -a settings   state=floating rectangle=500x380+1418+698
bspc rule -a simplemenu state=floating rectangle=$(gcbr 600 960)

#xrandr --output DP-3 --mode 3440x1440 -r 99.98 --pos 0x0 --rotate normal --output eDP-1 --primary --mode 1920x1080 --pos 3440x1200
#--rotate normal 
xrandr --output HDMI2  --mode 1920x1080 --pos 0x0 \
       --output eDP1 --mode 1920x1080 --primary
       # --output DP-2 --mode 1920x1080 --pos 0x0
#xrandr --output DP-1-3 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 1920x900

