#!/bin/sh

sxhkd &
bspc monitor eDP-1-1 -d I II III
#bspc monitor HDMI1 -d I II III
bspc monitor DP-1-3 -d IV V VI VII VIII IX X
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width	1
bspc config focused_border_color "#556633"
bspc config window_gap		0          
# bspc config focused_border_color "#bb5566"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox state=tiled
bspc rule -a Zathura state=tiled
#bspc rule -o -a stpopup state=floating rectangle=1918x380+0+$(expr 1078 - $(pgrep stpopup -f -c) \* 380)
bspc rule -a stpopup state=floating rectangle=1918x380+0+698
bspc rule -a player state=floating rectangle=500x380+1418+698
bspc rule -a settings state=floating rectangle=500x380+1418+698

#xrandr --output DP-3 --mode 3440x1440 -r 99.98 --pos 0x0 --rotate normal --output eDP-1 --primary --mode 1920x1080 --pos 3440x1200
xrandr --output DP-1-3 --mode 3440x1440 -r 99.98 --pos 0x0 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 3440x1200
#xrandr --output DP-1-3 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 1920x900
