#!/bin/sh
pkill sxhkd ; pkill picom ; pkill dunst ; pkill polybar
pkill steam ; pkill pipewire ; pkill pipewire-pulse
sxhkd &
pipewire & pipewire-pulse &
#picom --experimental-backends &
#$XDG_CONFIG_HOME/polybar/launch.sh &
dunst &
$HOME/.fehbg &
steam &
 
# bspc monitor DP-2 -d 
###################################################
#                     |    |    |    |    |   |   #    
#bspc monitor HDMI-A-0  -d  I    II   III  IV   V   VI #
#bspc monitor eDP -d  VII  IIX  IX   X           #
#bspc monitor eDP1  -d  I    II   III  IV   V   VI #
#                     |    |    |    |    |   |   #    
###################################################
bspc config border_width               1
bspc config focused_border_color       "#889999"
bspc config window_gap                 10

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true

bspc config pointer_follows_monitor    true
bspc config pointer_follows_focus      false
bspc config focus_follows_pointer      true

bspc rule -a "chromium" desktop='^1'   focus=on
bspc rule -a "Code"     desktop='^2'
bspc rule -a "Slack"    desktop='^10'  focus=on

bspc rule -a firefox state=tiled
bspc rule -a Zathura state=tiled
#bspc rule -o -a stpopup state=floating rectangle=1918x380+0+$(expr 1078 - $(pgrep stpopup -f -c) \* 380)
bspc rule -a stpopup    state=floating rectangle=1918x380+0+698
bspc rule -a player     state=floating rectangle=500x380+1418+698
bspc rule -a settings   state=floating rectangle=500x380+1418+698
bspc rule -a simplemenu state=floating rectangle=$(gcbr 500 760)

xset r rate 220 32

##xrandr --output DisplayPort-3 --mode 3440x1440 -r 99.98 --pos 0x0 --rotate normal \
xrandr --output DisplayPort-1-2 --mode 1920x1080
       # --output eDP-1 --primary --mode 1920x1080 --pos 3440x1200
#--rotate normal 
# xrandr --output DP-1-3  --mode 3440x1440 --pos 0x0 -r 99.98 --primary \
#        --output eDP-1-1 --mode 1920x1080 --pos 900x1440
#xrandr --output HDMI2  --mode 1920x1080 --pos 0x0 \
#       --output eDP1 --mode 1920x1080 --primary
       # --output DP-2 --mode 1920x1080 --pos 0x0
#xrandr --output DP-1-3 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 1920x900

