#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# CORONA VIRUS!!!
alias corona='curl "https://corona-stats.online/Germany?source=2" -Ss | grep Germany -B 3 -A 3'
alias corona-old='curl "https://corona-stats.online/Germany" -Ss | grep Germany -B 3 -A 1'

# WOL
alias wake-tower="wol --ipaddr=169.254.214.46 '4c:cc:6a:ff:18:34'"

# Voidlinux xbps
alias \
	xi="sudo xbps-install -S" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query -R" \
	xs="xbps-query -Rs" \

alias maxlight='lamp brightness 50 && lamp temperature 2650'
alias brightlight='lamp brightness 20 && lamp temperature 2500'
alias medlight='lamp brightness 8 && lamp temperature 2500'
alias dimlight='lamp brightness 0 && lamp temperature 1700'
#alias readings='while (true) {sensors | grep -e temp1 -e "Core 0" -e "Core 1" -e fan1 -B 1 && sleep 2.5 && clear}'
#alias show-me-packages="sudo pacman -Qi | grep 'Name\|Description' | less"

alias wf-cutout='$(wf-recorder -g "$(slurp)")'

#Verbosity and settings that you pretty much just always are going to want.
alias \
	ssh="kitty +kitten ssh" \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i --default-search 'ytsearch' " \
	yta="yt -x -f bestaudio/best" \
	yv="youtube-viewer" \
	yva="youtube-viewer -n" \
	ffmpeg="ffmpeg -hide_banner" \
	lolcat="lolcat -l"
# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	sd="sudo shutdown" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	bright="brightnessctl set"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

alias icat="kitty +kitten icat"

# Some other stuff
alias themes='find $(find ~/.themes /usr/share/themes/ -wholename "*/gtk-3.0" | sed -e "s/^\(.*\)\/gtk-3.0$/\1/") -wholename "*/gtk-2.0" | sed -e "s/.*\/\(.*\)\/gtk-2.0/\1"/'
#alias \
#	magit="nvim -c MagitOnly" \
#	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
#	weath="less -S ~/.local/share/weatherreport" \
